# Generated by Django 5.1.2 on 2024-11-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='precosse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.TextField(max_length=1000)),
            ],
        ),
    ]
